### ISSUE TITLE
Vocabulary DownLoad

### ISSUE THREAD

**Issue by xiaomofang** [ChanWoo25/SuperPoint-SLAM#4]
Hello,Would you like to put a link for SuperPoint-SLAM Vocabulary,that will help me a lot thanks!

**Comment by ChanWoo25** [comment]
Hi, Sorry for late answer,

Unfortunately, i lost my vocabulary file.
But you can create your own using "SuperPoint-SLAM/Thirdparty/DBoW2/*" source code. Look at codes in that directory. :)
