### ISSUE TITLE
Hello, I would like to ask where to download Voca/FinalVoc.txt 

### ISSUE THREAD

**Issue by BoyLazyA** [ChanWoo25/SuperPoint-SLAM#5]
Hello, I would like to ask where to download Voca/FinalVoc.txt

**Comment by ChanWoo25** [comment]
Hi,
Unfortunately, i lost my vocabulary file.
But you can create your own using "SuperPoint-SLAM/Thirdparty/DBoW2/*" source code. Look at codes in that directory. :)

**Comment by YznMur** [comment]
Hi @ChanWoo25 @BoyLazyA 
I have created voc.txt using [saveToTextFile](https://github.com/ChanWoo25/SuperPoint-SLAM/blob/b02441f5adcce766447921dca7e4dd53ba416ae6/src/System.cc#L114).
but Tracker doesn't work well:
```
[Tr]NoImgYet
[Tr]Init
[Tr]InitFail
```
Did u face the same problem?
Thanks in advance
